import { useState, useRef, useEffect } from 'react';
import { X, Pencil, RotateCcw, Trash2 } from 'lucide-react';
import { clsx } from 'clsx';
import type { ConsoleTab } from '../../../shared/types/console';
import { Input } from '../shared/FormField';
import { Button } from '../shared/Button';
import { ContextMenu, type ContextMenuItem } from '../shared/ContextMenu';

interface ConsoleTabsProps {
  tabs: ConsoleTab[];
  activeTabId: string | null;
  onSelectTab: (tabId: string) => void;
  onCloseTab: (tabId: string) => void;
  onRenameTab: (tabId: string, newName: string) => void;
  onCloseSession: (sessionId: string) => void;
}

interface TabItemProps {
  tab: ConsoleTab;
  isActive: boolean;
  isEditing: boolean;
  editValue: string;
  inputRef: React.RefObject<HTMLInputElement>;
  onSelectTab: (tabId: string) => void;
  onCloseTab: (tabId: string) => void;
  onCloseSession: (sessionId: string) => void;
  onStartRename: (tab: ConsoleTab) => void;
  onResetToAuto: (tab: ConsoleTab) => void;
  onEditValueChange: (value: string) => void;
  onKeyDown: (e: React.KeyboardEvent, tabId: string) => void;
  onBlur: (tabId: string) => void;
}

/**
 * Individual tab item
 * Name is managed server-side with auto-generation from CWD
 */
function TabItem({
  tab,
  isActive,
  isEditing,
  editValue,
  inputRef,
  onSelectTab,
  onCloseTab,
  onCloseSession,
  onStartRename,
  onResetToAuto,
  onEditValueChange,
  onKeyDown,
  onBlur,
}: TabItemProps): JSX.Element {
  const [contextMenu, setContextMenu] = useState<{ x: number; y: number } | null>(null);
  const displayName = tab.name;
  const isManuallyNamed = !tab.autoGenerated;

  const handleContextMenu = (e: React.MouseEvent): void => {
    e.preventDefault();
    setContextMenu({ x: e.clientX, y: e.clientY });
  };

  const contextMenuItems: ContextMenuItem[] = [
    {
      label: 'Rename',
      icon: <Pencil size={14} />,
      onClick: () => onStartRename(tab),
    },
    {
      label: 'Reset to Auto-Naming',
      icon: <RotateCcw size={14} />,
      onClick: () => onResetToAuto(tab),
      disabled: tab.autoGenerated, // Already auto-generated
    },
    { divider: true } as ContextMenuItem,
    {
      label: 'Close Tab',
      icon: <X size={14} />,
      onClick: () => onCloseTab(tab.id),
    },
    {
      label: 'Close Session',
      icon: <Trash2 size={14} />,
      onClick: () => onCloseSession(tab.sessionId),
      variant: 'danger' as const,
    },
  ];

  return (
    <>
      <div
        className={clsx(
          'flex items-center gap-2 px-4 py-3 border-r border-gray-200 dark:border-gray-700 min-w-[150px] max-w-[250px] cursor-pointer transition-colors',
          {
            'bg-white dark:bg-gray-800 border-b-2 border-b-blue-500': isActive,
            'bg-gray-100 dark:bg-gray-900 hover:bg-gray-200 dark:hover:bg-gray-800': !isActive,
          }
        )}
        onClick={() => !isEditing && onSelectTab(tab.id)}
        onContextMenu={handleContextMenu}
        title={
          isManuallyNamed
            ? `${displayName} (custom name)`
            : `${displayName} (auto-generated)`
        }
      >
      {isEditing ? (
        <Input
          ref={inputRef}
          type="text"
          value={editValue}
          onChange={(e) => onEditValueChange(e.target.value)}
          onKeyDown={(e) => onKeyDown(e, tab.id)}
          onBlur={() => onBlur(tab.id)}
          className="flex-1 text-sm"
          onClick={(e) => e.stopPropagation()}
        />
      ) : (
        <>
          <span
            className={clsx(
              'flex-1 truncate text-sm',
              isActive
                ? 'font-semibold text-gray-900 dark:text-gray-100'
                : 'text-gray-700 dark:text-gray-300'
            )}
          >
            {displayName}
          </span>
          {isManuallyNamed && (
            <Pencil size={12} className="text-gray-400 dark:text-gray-500 flex-shrink-0" title="Custom name" />
          )}
          <Button
            variant="ghost"
            size="icon-sm"
            onClick={(e) => {
              e.stopPropagation();
              onCloseTab(tab.id);
            }}
            className="flex-shrink-0 h-6 w-6 p-0 min-h-0"
            aria-label={`Close ${displayName}`}
          >
            <X size={14} />
          </Button>
        </>
      )}
    </div>

      <ContextMenu
        isOpen={Boolean(contextMenu)}
        x={contextMenu?.x ?? 0}
        y={contextMenu?.y ?? 0}
        items={contextMenuItems}
        onClose={() => setContextMenu(null)}
      />
    </>
  );
}

/**
 * Horizontal tab bar for managing console sessions.
 *
 * Features:
 * - Click tab to activate
 * - Right-click for context menu (rename, reset to auto, close tab, close session)
 * - Close button (×) for each tab
 * - Horizontal scrolling if too many tabs
 * - Visual indicator for manual names (pencil icon)
 * - Active tab highlighting
 */
export function ConsoleTabs({
  tabs,
  activeTabId,
  onSelectTab,
  onCloseTab,
  onRenameTab,
  onCloseSession,
}: ConsoleTabsProps): JSX.Element {
  const [editingTabId, setEditingTabId] = useState<string | null>(null);
  const [editValue, setEditValue] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (editingTabId && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [editingTabId]);

  const handleStartRename = (tab: ConsoleTab): void => {
    setEditingTabId(tab.id);
    setEditValue(tab.name);
  };

  const handleResetToAuto = (tab: ConsoleTab): void => {
    // Send empty string to reset to auto-generated
    onRenameTab(tab.id, '');
  };

  const handleSaveRename = (tabId: string): void => {
    // Always call onRenameTab, even if empty (empty = reset to auto)
    onRenameTab(tabId, editValue.trim());
    setEditingTabId(null);
    setEditValue('');
  };

  const handleCancelRename = (): void => {
    setEditingTabId(null);
    setEditValue('');
  };

  const handleKeyDown = (e: React.KeyboardEvent, tabId: string): void => {
    if (e.key === 'Enter') {
      handleSaveRename(tabId);
    } else if (e.key === 'Escape') {
      handleCancelRename();
    }
  };

  const handleBlur = (tabId: string): void => {
    handleSaveRename(tabId);
  };

  if (tabs.length === 0) {
    return (
      <div className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 px-6 py-3">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          No terminal sessions. Click "New Session" to get started.
        </p>
      </div>
    );
  }

  return (
    <div className="border-b border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-900">
      <div className="flex overflow-x-auto scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-600">
        {tabs.map((tab) => {
          const isActive = tab.id === activeTabId;
          const isEditing = tab.id === editingTabId;

          return (
            <TabItem
              key={tab.id}
              tab={tab}
              isActive={isActive}
              isEditing={isEditing}
              editValue={editValue}
              inputRef={inputRef}
              onSelectTab={onSelectTab}
              onCloseTab={onCloseTab}
              onCloseSession={onCloseSession}
              onStartRename={handleStartRename}
              onResetToAuto={handleResetToAuto}
              onEditValueChange={setEditValue}
              onKeyDown={handleKeyDown}
              onBlur={handleBlur}
            />
          );
        })}
      </div>
    </div>
  );
}
