/**
 * Console session types
 * Types for terminal session management in the Remote Console feature
 */

/**
 * Console session status
 */
export type ConsoleSessionStatus = 'running' | 'stopped' | 'error';

/**
 * Console session metadata
 */
export interface ConsoleSession {
  id: string;
  name: string;
  autoGenerated: boolean;
  currentDirectory: string;
  createdAt: string;
  status: ConsoleSessionStatus;
  pid?: number;
}

/**
 * Request to create a new console session
 */
export interface CreateSessionRequest {
  name?: string;
  initialDirectory?: string;
}

/**
 * Response from creating a console session
 */
export interface CreateSessionResponse {
  session: ConsoleSession;
}

/**
 * Response listing all console sessions
 */
export interface SessionListResponse {
  sessions: ConsoleSession[];
}

/**
 * Response from validating a console session
 * Different from kanban's ValidationResult (different optional fields)
 */
// @type-duplicate-allowed
export interface ConsoleSessionValidationResult {
  valid: boolean;
  session?: ConsoleSession;
}

/**
 * Response from getting session current working directory
 */
export interface SessionCwdResponse {
  sessionId: string;
  cwd: string;
  name?: string; // Updated session name (if auto-generated and changed)
}

/**
 * Console tab state (frontend only, for persistence)
 */
export interface ConsoleTab {
  id: string;
  sessionId: string;
  name: string;
  autoGenerated: boolean;
}

/**
 * Request to update session custom name
 */
export interface UpdateSessionNameRequest {
  name: string;
}

/**
 * VibeTunnel session creation response
 */
export interface VibeSessionResponse {
  session: {
    id: string;
  };
}

/**
 * VibeTunnel API session creation direct response
 */
export interface VibeSessionCreationResponse {
  sessionId: string;
}

/**
 * VibeTunnel session deletion response
 */
export interface VibeDeleteResponse {
  success: boolean;
}

/**
 * Terminal theme configuration (xterm.js compatible)
 * Defines colors for terminal rendering with salmon branding
 */
export interface TerminalTheme {
  background: string;
  foreground: string;
  cursor: string;
  cursorAccent: string;
  selectionBackground: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

/**
 * WebSocket message types for terminal communication
 */
export interface WebSocketMessage {
  type: 'input' | 'output' | 'resize' | 'ping' | 'pong';
  data: string | ArrayBuffer;
  sessionId?: string;
}

/**
 * Gesture event for touch interactions on mobile
 */
export interface GestureEvent {
  type: 'swipe' | 'scroll' | 'tap';
  direction?: 'up' | 'down' | 'left' | 'right';
  fingers: number;
  distance?: number;
  duration?: number;
}

/**
 * Keyboard input event with modifier keys
 */
export interface KeyboardInputEvent {
  key: string;
  modifiers: {
    ctrl: boolean;
    alt: boolean;
    shift: boolean;
    meta: boolean;
  };
  special?: boolean;
}

/**
 * WebSocket connection status
 */
export interface ConnectionStatus {
  connected: boolean;
  reconnecting: boolean;
  retryCount?: number;
  maxRetries?: number;
  error?: string;
}
